name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image
      run: |
        docker build -t hello-world-app .
        docker tag hello-world-app:latest 4385-1814-4064.dkr.ecr.us-west-2.amazonaws.com/hello-world-app:latest
        docker push <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world-app:latest

    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster hello-world-cluster --service hello-world-service --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
i
